//! Full-lifecycle scenarios: `ax init` → `ax up` → orchestrator turn
//! → validate. Unlike `orchestration_live.rs` (which uses a
//! pre-seeded config) and `init_live.rs` (which never starts the
//! daemon), this binary exercises the paths end-to-end so the
//! Completion Reporting Contract enforcement in `task_store` is
//! covered with real agents, not just unit-level stubs.
//!
//! Gated by `AX_E2E_LIVE=1`; requires `codex` + `tmux` + host codex
//! auth, same as the other live scenarios.

use std::path::PathBuf;
use std::time::Duration;

use ax_e2e::harness::{
    self, ax_down, ax_up, run_ax_init, start_daemon, start_root_orchestrator, HarnessError, Sandbox,
};

fn scenario_dir(name: &str) -> PathBuf {
    harness::repo_root()
        .join("e2e")
        .join("scenarios")
        .join(name)
}

fn live_enabled() -> bool {
    std::env::var("AX_E2E_LIVE")
        .map(|v| v == "1" || v.eq_ignore_ascii_case("true"))
        .unwrap_or(false)
}

/// Drive one full-lifecycle scenario. Structurally similar to
/// `drive_scenario` in `orchestration_live.rs`, but inserts an
/// `ax init` step before booting the daemon so the config is
/// generated by the setup agent instead of being pre-seeded.
fn drive_full_lifecycle_scenario(
    name: &str,
    init_args: &[&str],
    timeout: Duration,
    settle_window: Duration,
) -> Result<(), HarnessError> {
    let mut sandbox = Sandbox::new()?;
    let ax = sandbox.build_ax()?;
    sandbox.copy_scenario(&scenario_dir(name))?;

    // Init first. --no-refresh keeps the daemon out of this phase;
    // we boot it explicitly below so state-dir timing is
    // deterministic.
    let mut args: Vec<&str> = vec!["--no-refresh"];
    args.extend_from_slice(init_args);
    run_ax_init(&sandbox, &ax, &args)?;

    let _daemon = start_daemon(&sandbox, &ax)?;
    ax_up(&sandbox, &ax)?;
    let session = start_root_orchestrator(&sandbox, &ax)?;
    session.wait_idle(Duration::from_secs(120))?;
    let prompt = std::fs::read_to_string(scenario_dir(name).join("prompt.txt"))?;
    session.send_prompt(prompt.trim())?;

    let result =
        harness::wait_for_settled_success(timeout, Duration::from_secs(10), settle_window, || {
            let validate_ok = harness::run_validate_script(&sandbox, "validate.sh").is_ok();
            validate_ok && session.looks_idle()
        });
    if result.is_err() {
        dump_post_mortem(&sandbox, &session);
    }
    ax_down(&sandbox, &ax);
    result
}

/// Dump whatever state is salvageable from the sandbox before `Drop`
/// removes the tempdir. Captures the orchestrator pane, the
/// generated config, the persisted task state, and the project tree
/// so a failing scenario has enough evidence to diagnose without
/// re-running.
fn dump_post_mortem(sandbox: &Sandbox, session: &harness::OrchestratorSession) {
    eprintln!("\n========== POST-MORTEM ==========");
    eprintln!("sandbox root: {}", sandbox.root().display());
    eprintln!("project dir:  {}", sandbox.project().display());

    eprintln!("\n----- orchestrator pane -----");
    eprintln!("{}", session.capture_pane());

    let config = sandbox.config_path();
    if let Ok(body) = std::fs::read_to_string(&config) {
        eprintln!("\n----- .ax/config.yaml -----");
        eprintln!("{body}");
    }

    let task_state = sandbox.root().join("tasks-state.json");
    match std::fs::read_to_string(&task_state) {
        Ok(body) if body.trim().is_empty() => {
            eprintln!("\n----- tasks-state.json (empty) -----");
        }
        Ok(body) => {
            eprintln!("\n----- tasks-state.json -----");
            eprintln!("{body}");
        }
        Err(e) => {
            eprintln!("\n----- tasks-state.json unreadable: {e} -----");
        }
    }

    eprintln!("\n----- project tree -----");
    print_tree(sandbox.project(), 0, 4);
    eprintln!("==================================\n");
}

fn print_tree(dir: &std::path::Path, depth: usize, max_depth: usize) {
    if depth > max_depth {
        return;
    }
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    let mut entries: Vec<_> = read.flatten().collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let name = entry.file_name().to_string_lossy().into_owned();
        eprintln!("{:indent$}{name}", "", indent = depth * 2);
        if entry.file_type().is_ok_and(|ft| ft.is_dir()) {
            print_tree(&entry.path(), depth + 1, max_depth);
        }
    }
}

#[test]
fn init_and_implement_single_turn_completion() {
    if !live_enabled() {
        eprintln!("skipping: set AX_E2E_LIVE=1 to run live full-lifecycle scenarios");
        return;
    }
    // Single-workspace project, `--axis role` keeps init deterministic
    // (auto could legitimately pick either shape on a one-directory
    // repo). 12 minutes is enough for init (~1min) + orchestrator
    // boot (~30s) + one delegation turn; if it takes longer than
    // that the scenario is stuck and the post-mortem dump has what
    // we need.
    let result = drive_full_lifecycle_scenario(
        "init_and_implement",
        &["--codex", "--axis", "role"],
        Duration::from_secs(12 * 60),
        Duration::from_secs(15),
    );
    if let Err(e) = result {
        panic!("init_and_implement scenario failed: {e}");
    }
}
